### ISSUE TITLE
Is there any information about the latency in compute engine (CE) unit ?

### ISSUE THREAD

**Issue by ConstantPark** [SamsungLabs/Butterfly_Acc#1]
Hello. I have a question (initial_delay in compute unit).
I understand the compute_cycles.
But i don't know the initial_delay.
Could you give me a detailed information ?

**Comment by os-hxfan** [comment]
Thanks for your interest and attention!

The initial delay means the time spent on filling the pipeline chain at the beginning, You can understand it as the latency (time of getting the first output) in a specific module.  The formula looks complicated because this value was cross-validated from the Vivado simulation waveform....

PS: sorry for the delayed reply. I didn't receive the notification as this repo is hosted by the company account due to the IP policy.  In the further If you leave any comments on github, pls also drop me an email at hongxiang.f@samsung.com.  Or just drop your questions at my personal email: [hongxiangfan@ieee.org](mailto:hongxiangfan@ieee.org) or [hf384@cl.cam.ac.uk](mailto:hf384@cl.cam.ac.uk)
