### ISSUE TITLE
Confusion on accuracy test code

### ISSUE THREAD

**Issue by lvdongxu** [SamsungLabs/Butterfly_Acc#4]
Hi, thank you for your open-sourced excellent work and code!

I'm learning the butterfly transformation and get confused in software/accuracy/code/attention.py that you did not use the butterfly linear transformation in Q, K, V generation as you said in your MICRO paper. But I find you involve the butterfly linear layers in software/speed/src/models/bfly_fnet_model.py.

Does that have no effect on the accuracy? or maybe just a mistake.

Look forward to your reply soon.

**Comment by os-hxfan** [comment]
Hi, Thanks a lot for your attention on our work.

1. The code in software/accuracy/code/attention.py with the `softmax` option is not used in our final accuracy test shown in the paper, because in the end we found the most efficient way is to use `fft`.  
2.  You can easily replace the Linear layer with Butterfly linear layer for your own test.  From our previous experiments, it almost has no impact on the final accuracy of the language task we tested.  We probably just forgot to update this part, because it is not used when we get the best performance.

Hope the above helpful.
