### ISSUE TITLE
Pretrained FABNet

### ISSUE THREAD

**Issue by abhishektyaagi** [SamsungLabs/Butterfly_Acc#5]
Hi,
I have been trying to run the experiments in `fab_quant`  folder to have my own network, but to no avail due to some dependency issues. While I work on solving those, is it possible for the authors to share details about any checkpoints available in public domain for any configuration of FABNet?

**Comment by os-hxfan** [comment]
Thanks for your interest.   Since the training from scratch doesn't take much time for FABNet, we didn't provide pre-trained models. You will need to train from scratch on your own GPU. It is just several hours of training,

You can try the train from scratch following this instruction: https://github.com/SamsungLabs/Butterfly_Acc/blob/main/script_figs/README.md  
The part "Table 3" is what you need to look at.  You can start from there as a starting point to familiarize the code.

Hope this is helpful.
